name: main

on:
  workflow_dispatch:
  push:

# This allows one Build workflow run to interrupt another
# https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#concurrency
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      COVERALLS_REPO_TOKEN: '${{ secrets.COVERALLS_REPO_TOKEN }}'
      COVERALLS_GIT_COMMIT: '${{ github.sha }}'
      COVERALLS_GIT_BRANCH: '${{ github.ref }}'

    steps:
      - name: Checkout üõéÔ∏è
        uses: actions/checkout@v2

      - name: Turnstyle
        uses: softprops/turnstyle@v1
        timeout-minutes: 10
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Yarn Cache üíæ
        id: yarn-cache
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-modules

      - name: Install Node.js üîß # This example project is built using npm and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
        uses: actions/setup-node@v3
        with:
          node-version: '14'
          check-latest: true

      - run: yarn install
        if: steps.yarn-cache.outputs.cache-hit != 'true'

      - name: Build üë∑
        run: |
          yarn test
        env:
          CI: true

      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - uses: mikeal/merge-release@master
        if: github.ref == 'refs/heads/master'
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
